spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true

env:
  test4
girl:
  name: lily
  age: 19
  
#PRODUCT:
#  ribbon:
#    #自定义负载均衡策略为随机
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
